{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hangar-cloud.fullname" . }}-secrets
  labels:
    {{- include "hangar-cloud.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  jwt-secret: {{ .Values.config.auth.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}
  {{- if .Values.config.stripe.apiKey }}
  stripe-api-key: {{ .Values.config.stripe.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
